name: 'chromos-channels'
description: 'Middleware functions and wrappers for CPM'
version: '1.0.1'
packages:
  chromos:
bits:
  zeromq: '4.3.2'
test_bits:
  cest: '1.0'
link_options:
  libraries: ['pthread']