name: 'chromos-actors'
description: 'Middleware functions and wrappers for CPM'
version: '1.0.1'
packages:
  chromos:
bits:
  zeromq: '4.3.2'
  chromos-channels: '1.0'
test_bits:
  cest: '1.0'
link_options:
  libraries: ['pthread']