name: C/C++ CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip3 install --upgrade cpm-cli
          sudo apt install -yq ninja-build g++
      - name: Test and Build Channels
        working-directory: ./chromos-channels
        run: |
          cpm install
          cpm test
          cpm build
      - name: Test and Build Actors
        working-directory: ./chromos-actors
        run: |
          cpm install
          cpm test
          cpm build
