name: C/C++ CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x86
      - name: Install dependencies
        run: |
          pip3 install --upgrade cpm-cli
          cpm install
      - name: Test
        run: |
          cpm test
      - name: Build
        run: |
          cpm build
